apiVersion: v1
kind: Service
metadata:
  name: main-nginx
  namespace: edu-aleksandr-evstigneev
spec:
  type: NodePort
  selector:
    app: main-nginx
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
